//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digital_X_Ray.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DXREntities : DbContext
    {
        public DXREntities()
            : base("name=DXREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_cargarCaso_Result> sp_cargarCaso(string numeroCaso)
        {
            var numeroCasoParameter = numeroCaso != null ?
                new ObjectParameter("numeroCaso", numeroCaso) :
                new ObjectParameter("numeroCaso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cargarCaso_Result>("sp_cargarCaso", numeroCasoParameter);
        }
    
        public virtual ObjectResult<sp_cargarCasos_Result> sp_cargarCasos(string codigo, string fechaInicio, string fechaFin)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(string));
    
            var fechaFinParameter = fechaFin != null ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cargarCasos_Result>("sp_cargarCasos", codigoParameter, fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<sp_cargarImagenesDeCaso_Result> sp_cargarImagenesDeCaso(Nullable<int> codigoCaso)
        {
            var codigoCasoParameter = codigoCaso.HasValue ?
                new ObjectParameter("codigoCaso", codigoCaso) :
                new ObjectParameter("codigoCaso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cargarImagenesDeCaso_Result>("sp_cargarImagenesDeCaso", codigoCasoParameter);
        }
    
        public virtual int sp_editarCaso(Nullable<int> codigoCaso, string problema, string trabajo, string observaciones, string codigoEstado)
        {
            var codigoCasoParameter = codigoCaso.HasValue ?
                new ObjectParameter("codigoCaso", codigoCaso) :
                new ObjectParameter("codigoCaso", typeof(int));
    
            var problemaParameter = problema != null ?
                new ObjectParameter("problema", problema) :
                new ObjectParameter("problema", typeof(string));
    
            var trabajoParameter = trabajo != null ?
                new ObjectParameter("trabajo", trabajo) :
                new ObjectParameter("trabajo", typeof(string));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("observaciones", observaciones) :
                new ObjectParameter("observaciones", typeof(string));
    
            var codigoEstadoParameter = codigoEstado != null ?
                new ObjectParameter("codigoEstado", codigoEstado) :
                new ObjectParameter("codigoEstado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_editarCaso", codigoCasoParameter, problemaParameter, trabajoParameter, observacionesParameter, codigoEstadoParameter);
        }
    
        public virtual ObjectResult<sp_listarProductos_Result> sp_listarProductos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listarProductos_Result>("sp_listarProductos");
        }
    
        public virtual ObjectResult<sp_login_Result> sp_login(string usuario, string contrasena)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_login_Result>("sp_login", usuarioParameter, contrasenaParameter);
        }
    
        public virtual int sp_subirImagenes(Nullable<int> codigoCaso, string imagen)
        {
            var codigoCasoParameter = codigoCaso.HasValue ?
                new ObjectParameter("codigoCaso", codigoCaso) :
                new ObjectParameter("codigoCaso", typeof(int));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("imagen", imagen) :
                new ObjectParameter("imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_subirImagenes", codigoCasoParameter, imagenParameter);
        }
    }
}
